CREATE TABLE IF NOT EXISTS public.item (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(255) NULL,
	created_datetime timestamp NULL,
	updated_by varchar(255) NULL,
	updated_datetime timestamp NULL,
	description varchar(500) NULL,
	"name" varchar(255) NULL,
	price float8 NULL,
	quantity int4 NULL,
	CONSTRAINT item_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.purchases (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(255) NULL,
	created_datetime timestamp NULL,
	updated_by varchar(255) NULL,
	updated_datetime timestamp NULL,
	item_id int4 NULL,
	quantity int4 NULL,
	total_price float8 NULL,
	CONSTRAINT purchases_pkey PRIMARY KEY (id)
);